name: Release a Dev Build

on:
  workflow_dispatch: #Manual Trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create a Dev Build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute Gradle build
        run: chmod +x gradlew ; ./gradlew build --scan

      - name: Upload test build
        uses: actions/upload-artifact@v4
        with:
          name: test-build
          path: |
            build/libs/
            !build/libs/*-core.jar
            !build/libs/*-deobf.jar
            !build/libs/*-sources.jar

      - name: Upload sources
        uses: actions/upload-artifact@v4
        with:
          name: sources
          path: |
            build/libs/*-core.jar
            build/libs/*-deobf.jar
            build/libs/*-sources.jar
